permalink:           /:categories/:title/

title:               bonina.eu
url:                 https://bonina.eu
paginate:            4

description: 'where you find tips and tutorials about technology'

timezone: America/New_York

#highlighter: rouge

sass:
  sass_dir:          _sass
  style:            :compressed

pages_list:
  Web: '/web'
  Software: '/software'
  Hardware: '/hardware'
  About: '/about'

#plugins:
#  - jekyll-sitemap
