permalink:           /:categories/:title/

title:               Bonina
tagline:             eu
url:                 https://bonina.eu
paginate:            3
baseurl:             "https://bonina.eu"

highlighter: rouge

sass:
  sass_dir:          _sass
  style:            :compressed

pages_list:
  Tech: '/tech'
  Finance: '/finance'
  Health: '/health'
  About: '/about'
