permalink:           /:categories/:title/

title:               Bonina
tagline:             eu
url:                 https://bonina.eu
paginate:            3

highlighter: rouge

sass:
  sass_dir:          _sass
  style:            :compressed

pages_list:
  Web: '/web'
  Software: '/software'
  Hardware: '/hardware'
  About: '/about'

plugins:
  - jekyll-sitemap
